name: Access Google via Headless Browser

on: 
  push:
    branches:
      - main

jobs:
  access_google:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        instance: [1, 2, 3, 4, 5]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Add delay based on instance
      run: |
        if [ "${{ matrix.instance }}" -eq 2 ]; then sleep 12; fi
        if [ "${{ matrix.instance }}" -eq 3 ]; then sleep 24; fi
        if [ "${{ matrix.instance }}" -eq 4 ]; then sleep 36; fi
        if [ "${{ matrix.instance }}" -eq 5 ]; then sleep 48; fi

    - name: Create access-google.js script
      run: |
        echo "const puppeteer = require('puppeteer');" > access-google.js
        echo "const os = require('os');" >> access-google.js  # Added os module to get CPU usage
        echo "" >> access-google.js
        echo "(async () => {" >> access-google.js
        echo "    const browser = await puppeteer.launch({" >> access-google.js
        echo "        headless: true," >> access-google.js
        echo "        args: [" >> access-google.js
        echo "            '--no-sandbox'," >> access-google.js
        echo "            '--disable-setuid-sandbox'," >> access-google.js
        echo "            '--proxy-server=http://geo-dc.floppydata.com:10080'" >> access-google.js
        echo "        ]" >> access-google.js
        echo "    });" >> access-google.js
        echo "    const page = await browser.newPage();" >> access-google.js
        echo "" >> access-google.js
        echo "    // Set proxy authentication" >> access-google.js
        echo "    await page.authenticate({" >> access-google.js
        echo "        username: 'okycMaVnB0goNgIe'," >> access-google.js
        echo "        password: 'fUtzsxTC8C8FEURq'" >> access-google.js
        echo "    });" >> access-google.js
        echo "" >> access-google.js
        echo "    // Get new IP address" >> access-google.js
        echo "    await page.goto('http://httpbin.org/ip');" >> access-google.js
        echo "    const ipResponse = await page.content();" >> access-google.js
        echo "    console.log('New IP Address:', ipResponse);" >> access-google.js
        echo "" >> access-google.js
        echo "    // Navigate to Google" >> access-google.js
        echo "    await page.goto('https://preeminent-speculoos-789b5a.netlify.app/');" >> access-google.js
        echo "" >> access-google.js
        echo "    // Print page title" >> access-google.js
        echo "    const title = await page.title();" >> access-google.js
        echo "    console.log('Page Title:', title);" >> access-google.js
        echo "" >> access-google.js
        echo "    // Display CPU usage after showing the page title" >> access-google.js
        echo "    const cpuUsage = os.loadavg();" >> access-google.js
        echo "    console.log('CPU Load Average (1, 5, 15 mins):', cpuUsage);" >> access-google.js
        echo "" >> access-google.js
        echo "    // Keep the browser open indefinitely" >> access-google.js
        echo "    await new Promise(() => {});" >> access-google.js
        echo "})();" >> access-google.js

    - name: Install Puppeteer
      run: npm install puppeteer

    - name: Run headless browser script
      run: node access-google.js
